6 create third lecture solution
grygy/pv217-microservices-materials pull request #9
Opened 2024-01-22 22:15 UTC by grygy

2024-01-22 22:17 UTC, grygy commented on 03/passenger-service/src/test/java/cz/muni/fi/airportmanager/passengerservice/grpc/FlightCancellationServiceTest.java
> +        var response = flightCancellationStub.cancelFlight(FlightCancellationRequest.newBuilder().setId(1).setReason("Unknown").build()).await().indefinitely();
This cannot find test grpc service

2024-02-08 16:10 UTC, xstefank requested changes

2024-02-19 20:07 UTC, grygy commented on 03/README.md
> +Note that `FlightServiceApplication` extends `Application` class from `jakarta.ws.rs.core.Application`. It's kinda "
Used formal definition

2024-02-19 20:08 UTC, grygy commented on 03/README.md
> +| HTTP/1.1      | HTTP/2                       |
Yes true. Removed

2024-02-19 20:16 UTC, grygy commented on 03/README.md
> +| JSON, XML     | Protocol Buffers             |
Updated table

2024-02-19 20:16 UTC, grygy commented on 03/README.md
> +| Stateless     | Bidirectional streaming      |
Updated table

2024-02-19 20:16 UTC, grygy commented on 03/README.md
> +| Client-server | Client-server, server-server |
Table updated

2024-02-19 20:42 UTC, grygy commented on 03/README.md
> +#### 4.3. Test it
Honestly, I don't know how to use the new dev UI to test grpc

<img width="1702" alt="image" src="https://github.com/grygy/pv217-microservices-materials/assets/49610117/c5db111f-b3a6-47a3-a09a-4a457fc6901f">

2024-02-19 20:44 UTC, grygy commented on 03/flight-service/src/main/resources/application.properties
> +quarkus.grpc.clients.passenger-service.host=localhost
Doesn't look like url exists in `GrpcClientconfiguration`

2024-02-20 10:21 UTC, xstefank commented on 03/flight-service/src/main/resources/application.properties
> +quarkus.grpc.clients.passenger-service.host=localhost
quarkus.grpc.clients.passenger-service.url?

2024-02-21 11:52 UTC, xstefank requested changes

2024-03-02 10:45 UTC, grygy commented
moved to #20

2024-03-02 10:45 UTC, closed without merging

2024-03-02 14:15 UTC, grygy commented on 03/README.md
> +Note that `FlightServiceApplication` extends `Application` class from `jakarta.ws.rs.core.Application`. It defines the components of an application and supplies additional meta-data. It's not necessa
Changed

2024-03-02 14:16 UTC, grygy commented on 03/flight-service/src/main/resources/application.properties
> +quarkus.grpc.clients.passenger-service.host=localhost
Yes, there is no url.

2024-03-02 14:20 UTC, grygy commented on 03/README.md
> +#### 4.3. Test it
When I moved proto files dev ui grpc works.

2024-03-02 21:40 UTC, grygy commented on 03/README.md
> +It is also possible to run compile elsewhere and just mark the generated sources as sources dir by right click.
Moved to the troubleshoot section because with the proto file moved to the service, it idea works as expected.